site_name: IBM Maximo Labs
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Carlos Ferreira
site_description: "Documentation for Maximo Asset Manager Hands on Lab"
google_analytics: ['UA-159649729-1', 'auto']
nav:
  - Home: 
    - Welcome to the Maximo Labs: index.md
  - Monitor Lab:
    - Get Started: monitor-hol/monitor-index.md
    - Pre-Requisites: monitor-hol/facilitator_instructions.md
    - Exercises:
        - 1.  Connect Devices: monitor-hol/connect_device.md
        - 2.  Monitor Assets: monitor-hol/monitor_asset_devices.md
        - 3.  Monitor Anomalies: monitor-hol/monitor_anomalies.md
        - 4.  Create Service Requests: monitor-hol/service_request.md
        - 5.  Add Image Cards: monitor-hol/add_imagecard.md
        - 6.  Add Dimensions: monitor-hol/create_dimensions.md
        - 7.  Add Value Cards: monitor-hol/addvaluecard.md

  - Visual Inspection Lab:
    - Get Started: mvi-hol/mvi-index.md
    - Pre-Requisites: mvi-hol/prereqs.md
    - Excercises:
        - 1.1 DataSets: mvi-hol/exerciseOne/exercise1-1.md
        - 1.2 Train and Deploy Model: mvi-hol/exerciseOne/exercise1-2.md
        - 1.3 Create Project: mvi-hol/exerciseOne/exercise1-3.md
        - 2.1 Create Inspection: mvi-hol/exerciseTwo/exercise2-1.md
        - 2.2 Conduct Inspection: mvi-hol/exerciseTwo/exercise2-2.md
        - 2.3 Dashboard Configuration: mvi-hol/exerciseTwo/exercise2-3.md
    - Next Steps: mvi-hol/nextsteps.md
    - Troubleshooting: mvi-hol/troubleshoot.md
  - About:
    - Contributors: contributors.md
    - Contributing: about.md
theme: readthedocs
markdown_extensions:
  - attr_list
