site_name: IBM Maximo Labs
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Carlos Ferreira
site_description: "Documentation for Maximo Asset Manager Hands on Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site


nav:
  - Home: 
    - Welcome to the Maximo Labs: index.md
  - About:
    - Contributors: contributors.md
    - Contributing: about.md
theme: readthedocs

markdown_extensions:
  - attr_list
